# Generated by Django 5.0.6 on 2024-05-22 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('endereco', models.CharField(max_length=256)),
                ('preco_min', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preco_max', models.DecimalField(decimal_places=2, max_digits=8)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('data_hora_sorteio', models.DateTimeField()),
                ('usuario_criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Admin'), (2, 'AdminGrupo'), (3, 'Participante')], default=3)),
                ('nao_pode_presentear_alguem', models.BooleanField(default=False)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participante_grupo', to='AmigoSecreto.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('token', models.CharField(blank=True, max_length=256, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ManyToManyField(related_name='restricao_grupo', to='AmigoSecreto.grupo')),
                ('presenteado', models.ManyToManyField(related_name='restricao_presenteado', to=settings.AUTH_USER_MODEL)),
                ('presenteador', models.ManyToManyField(related_name='restricao_presenteador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ManyToManyField(related_name='sorteio_grupo', to='AmigoSecreto.grupo')),
                ('presenteado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorteio_presenteado', to=settings.AUTH_USER_MODEL)),
                ('presenteador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorteio_presenteador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
